version: 1
disable_existing_loggers: False
formatters:
  default:
    (): 'uvicorn.logging.DefaultFormatter'
    fmt: '%(asctime)s %(levelprefix)-9s %(name)s -: %(message)s'
  access:
    (): 'uvicorn.logging.AccessFormatter'
    fmt: '%(asctime)s %(levelprefix)-9s %(name)s -: %(client_addr)s - "%(request_line)s" %(status_code)s'
handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  access:
    class: logging.handlers.RotatingFileHandler
    formatter: access
    filename: logs/access.log
    maxBytes: 5000000
    backupCount: 5
  error:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/error.log
    maxBytes: 5000000
    backupCount: 5
loggers:
  uvicorn:
    level: INFO
    handlers:
      - default
  uvicorn.error:
    level: INFO
  uvicorn.access:
    level: INFO
    propagate: False
    handlers:
      - access
